#!/bin/bash

#
# hybridswitch - simple icon tray to switch enviroinment
# Copyright (C) 2011 Eugenio "g7" Paolantonio and the Semplice Team. All rights reserved.
# Work released under the GNU GPL license, version 3 or later.
#

error() {
	echo "$@" >&2
	exit 1
}

return_icon() {
	# Returns icon into the current icon theme
	theme="$2"
	[ -z "$theme" ] && theme="`cat ~/.gtkrc-2.0 | grep 'gtk-icon-theme' | cut -d '=' -f2 | sed 's/\"//g'`"
	if [ -d "/usr/share/icons/$theme" ]; then
		dir="/usr/share/icons/$theme"
	elif [ -d ~/.icons/$theme ]; then
		# else try with ~/.icons
		dir="~/.icons/$theme"
	else
		# dummy icon
		echo "info"
	fi
			
	if [ ! -e "$dir/24x24/$1.png" ]; then
		# File doesn't exists; see inherits and try on that theme
		inh="`cat $dir/index.theme | grep 'Inherits' | cut -d '=' -f2`"
		[ -z "$inh" ] && return
		return_icon $1 $inh
		return
	else
		echo "$dir/24x24/$1.png"
	fi
}

[ -e ~/.hybridstate ] || error "No hybridstate found. Starting this script has no sense."

tray() {
	# The tray.
	
	# First read hybridstate
	state="`cat ~/.hybridstate`"
	
	if [ "$state" = "geeky" ]; then
		to="simple"
	else
		to="geeky"
	fi
	
	# Then set tooltip...
	tooltip="Click me to switch to $to mode."
	
	# Now show the tray
	zenity --notification --text="$tooltip" --window-icon="`return_icon places/user-desktop`"
	if [ "$?" = "0" ]; then
		# The user has really clicked on the tooltip, so switch!
		semplice-openbox-autostart --switch
		
		tray # Reshow tray
	fi
}

tray
