#!/bin/sh
#
# open-mixer - wrapper to open the right mixer, at the right time.
# Copyright (C) 2014  Semplice Project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# Authors:
#    Eugenio "g7" Paolantonio <me@medesimo.eu>
#

# NOTE: the goal of this script is simply to *try* to run the right
# mixer given the current settings (pulseaudio enabled/disabled).
# It *doesn't* check for the existance of the mixers.

if [ -x /usr/bin/pulseaudio ] && pulseaudio --check; then
	# Pulseaudio detected
	exec pavucontrol
else
	# No pulseaudio
	exec cymbaline
fi
