#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# semplice-about: about dialog for semplice
# Copyright (C) 2009-12 Semplice Project. All rights reserved.
#
# This file is part of the semplice-utilities package
#

import sys, os
#import pyGtk
#pyGtk.require("2.0")
#import Gtk, Gtk.gdk

from gi.repository import Gtk, GdkPixbuf

import t9n.library
_ = t9n.library.translation_init("semplice-utilities")

if os.path.exists("/etc/semplice-live-mode"):
	LIVE = True
else:
	LIVE = False

if os.path.exists("/usr/share/semplice-utilities/semplicelogo.png"):
	logof = "/usr/share/semplice-utilities/semplicelogo.png"
else:
	logof = "./semplicelogo.png"

class Info:
	def __init__(self):	
		self.about = Gtk.AboutDialog()
		
		logo = GdkPixbuf.Pixbuf.new_from_file(logof)
		self.about.set_default_icon_name("help-about")
		
		self.about.connect('destroy', Gtk.main_quit)
		
		self.get_build()
		self.get_version()

		self.license = []
		self.license.append(_("All work done by the Semplice Project, if not declared, is released under the GNU GPL license, see below."))
		self.license.append("""
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
""")
		self.license.append(_("For other applications, see /usr/share/doc/<packagename>/copyright."))
		self.license.append(_("The most common licenses are available in /usr/share/common-licenses."))
		
		self.license = "\n".join(self.license)
				
		# Details
		self.about.set_logo(logo)
		if LIVE == True:
			typ = "Live" # We're into the Live System
		else:
			typ = "Desktop" # We're into the Semplice System (installed system)

		self.about.set_program_name("Semplice %s" % typ)

		self.about.set_version("%s (%s)" % (self.version, self.arch)) # Version
		#self.about.set_version(self.arch)
		self.about.set_copyright("Copyright (C) 2009-13 Semplice Project") # Copyright
		self.about.set_comments(_("A simple, lightweight, fast and Debian-based GNU/Linux distribution."))
		self.about.set_license(self.license)
		self.about.set_wrap_license(True)
	   	self.about.set_website("http://semplice-linux.org")
		self.about.set_website_label("semplice-linux.org")
		self.about.add_credit_section(_("The awesome"), [
			"Eugenio \"g7\" Paolantonio <me@medesimo.eu>",
			"Luca Boncore <sidtux@onblu.net>",
			"Giuseppe \"GsC_RuL3Z\" Corti <giuseppe@infiniteloop.pro>",
			])
		
		self.about.run()
		sys.exit(0)
		
	def get_build(self):
		if os.path.exists("/etc/semplice-build"):
			# 32-bit
			self.arch = "i386"
		elif os.path.exists("/etc/semplice64-build"):
			# 64-bit
			self.arch = "amd64"
		else:
			self.arch = "unknown"
	
	def get_version(self):
		# FIXME: Since Beta 1, semplice_version is in system-base which is ALWAYS installed.
		# FIXME:  We need to fix, maybe with a check of the installed packages.
		if os.path.exists("/etc/semplice_version"):
			with open("/etc/semplice_version") as f:
				self.version = f.readline().replace("\n","")
		else:
			self.version = "rolling"
	
if __name__ == "__main__":
	import signal
	signal.signal(signal.SIGINT, signal.SIG_DFL)

	dialog = Info()
	Gtk.main()
