#!/bin/bash

#
# semplice-help-irc: launch xchat on irc.freenode.net/semplice{-it}
# Copyright (C) 2012 Semplice Team. All rights reserved.
# This script is released under the terms of the GNU GPL license, version 3 or later.
#

if [ ! -e "/usr/bin/xchat" ]; then
	echo "E: XChat is not installed!"
	exit 1
fi

# t9n
source gettext.sh

export TEXTDOMAIN="semplice-utilities"
export TEXTDOMAINDIR="/usr/share/locale"

# String
__title="`gettext \"Enter your username\"`"
__sub="`gettext \"Please enter the username to use for the login on Semplice's support channel.\"`"

# Get language (strip it from the locale)
LANGUAGE="`echo $LANG | cut -d '_' -f1`"
	
# Get appropriate channel and server
if [ "$LANGUAGE" = "it" ]; then
	CHAN="semplice-it"
	SRV="calvino.freenode.net"
else
	CHAN="semplice"
	SRV="irc.freenode.net"
fi
	
# Prompt for name, if any
if [ ! -d $HOME/.semplice-help-irc ]; then
	username="`zenity --entry --text=\"$__sub\" --title=\"$__title\"`"
	[ -z "$username" ] && exit 1 # Canceled
	
	mkdir ~/.semplice-help-irc
	cat > ~/.semplice-help-irc/xchat.conf <<EOF
version = 2.8.8
auto_save = 1
auto_save_url = 0
away_auto_unmark = 0
away_reason = Busy
away_show_message = 0
away_show_once = 1
away_size_max = 300
away_timeout = 60
away_track = 1
completion_amount = 5
completion_auto = 0
completion_sort = 0
completion_suffix = ,
completion_cinsens = 0
dcc_auto_chat = 0
dcc_auto_resume = 1
dcc_auto_send = 2
dcc_blocksize = 1024
dcc_completed_dir = 
dcc_dir = $HOME/.semplice-help-irc/downloads
dcc_fast_send = 1
dcc_global_max_get_cps = 0
dcc_global_max_send_cps = 0
dcc_ip = 
dcc_ip_from_server = 0
dcc_max_get_cps = 0
dcc_max_send_cps = 0
dcc_permissions = 384
dcc_port_first = 0
dcc_port_last = 0
dcc_remove = 0
dcc_save_nick = 0
dcc_send_fillspaces = 0
dcc_stall_timeout = 60
dcc_timeout = 180
dnsprogram = host
flood_ctcp_num = 5
flood_ctcp_time = 30
flood_msg_num = 5
flood_msg_time = 30
gui_auto_open_chat = 1
gui_auto_open_dialog = 1
gui_auto_open_recv = 1
gui_auto_open_send = 1
gui_dialog_height = 256
gui_dialog_left = 0
gui_dialog_top = 0
gui_dialog_width = 500
gui_hide_menu = 1
gui_input_spell = 1
gui_input_style = 0
gui_join_dialog = 1
gui_lagometer = 1
gui_mode_buttons = 0
gui_pane_left_size = 100
gui_pane_right_size = 104
gui_quit_dialog = 1
gui_slist_select = 0
gui_slist_skip = 0
gui_throttlemeter = 1
gui_topicbar = 1
gui_tray = 0
gui_tray_flags = 0
gui_tweaks = 0
gui_ulist_buttons = 0
gui_ulist_doubleclick = QUOTE WHOIS %s %s
gui_ulist_hide = 0
gui_ulist_left = 0
gui_ulist_pos = 3
gui_ulist_resizable = 1
gui_ulist_show_hosts = 0
gui_ulist_sort = 0
gui_ulist_style = 0
gui_url_mod = 4
gui_usermenu = 0
gui_win_height = 400
gui_win_left = 689
gui_win_save = 1
gui_win_state = 0
gui_win_top = 327
gui_win_width = 640
input_balloon_chans = 0
input_balloon_hilight = 0
input_balloon_priv = 0
input_balloon_time = 20
input_beep_chans = 0
input_beep_hilight = 1
input_beep_msg = 1
input_command_char = /
input_filter_beep = 0
input_flash_chans = 0
input_flash_hilight = 1
input_flash_priv = 1
input_perc_ascii = 0
input_perc_color = 0
input_tray_chans = 0
input_tray_hilight = 1
input_tray_priv = 1
irc_auto_rejoin = 0
irc_ban_type = 2
irc_conf_mode = 0
irc_extra_hilight = 
irc_hide_version = 0
irc_id_ntext = 
irc_id_ytext = 
irc_invisible = 0
irc_join_delay = 3
irc_logging = 0
irc_logmask = %n-%c.log
irc_nick1 = ${username}
irc_nick2 = ${username}_
irc_nick3 = ${username}__
irc_nick_hilight = 
irc_no_hilight = NickServ,ChanServ
irc_part_reason = Forza Inter
irc_quit_reason = Forza Inter
irc_raw_modes = 0
irc_real_name = Semplice-help-irc user!
irc_servernotice = 0
irc_skip_motd = 0
irc_user_name = $username
irc_wallops = 0
irc_who_join = 1
irc_whois_front = 0
net_auto_reconnect = 1
net_auto_reconnectonfail = 0
net_bind_host = 
net_ping_timeout = 0
net_proxy_auth = 0
net_proxy_host = 
net_proxy_pass = 
net_proxy_port = 0
net_proxy_type = 0
net_proxy_use = 0
net_proxy_user = 
net_reconnect_delay = 10
net_throttle = 1
notify_timeout = 15
notify_whois_online = 0
perl_warnings = 0
sound_command = 
sound_dir = $HOME/.semplice-help-irc/sounds
stamp_log = 1
stamp_log_format = %b %d %H:%M:%S 
stamp_text = 1
stamp_text_format = [%H:%M] 
tab_chans = 0
tab_dialogs = 1
tab_layout = 0
tab_new_to_front = 2
tab_notices = 0
tab_pos = 7
tab_position = 2
tab_server = 0
tab_small = 0
tab_sort = 1
tab_trunc = 20
tab_utils = 1
text_background = 
text_color_nicks = 1
text_font = Droid Sans Mono 10
text_indent = 1
text_max_indent = 256
text_max_lines = 500
text_replay = 1
text_show_marker = 1
text_show_sep = 1
text_stripcolor = 0
text_thin_sep = 1
text_tint_blue = 195
text_tint_green = 195
text_tint_red = 195
text_transparent = 0
text_wordwrap = 1
EOF

fi

exec xchat --url="irc://$SRV:6667/$CHAN" --cfgdir=$HOME/.semplice-help-irc
